base:
    is_dev: false
mysql_info:
    host: 118.31.236.23
    port: 3306
    username: test_write
    password: Q^pI&Vq!Hf9FokCm
    database: med_primary
out_dir: ./model
url_tag: json
language: 中 文
db_tag: gorm
simple: false
is_web_tag: true
is_web_tag_pk_hidden: true
singular_table: true
is_foreign_key: true
is_out_sql: false
is_out_func: true
is_gui: true
is_table_name: false
is_null_to_point: false

